### ISSUE TITLE
App crashes when trying to display notifications

### ISSUE THREAD

**Issue by atomwaffel** [maltaisn/another-notes-app#65] opened 2022-04-18 14:09 UTC
Notifications don't work on my S22 so I left the app open while waiting for one and the result is a crash every time. I already tried clearing the cache and reinstalling.

**Comment by maltaisn** [comment] 2022-06-24 17:09
Duplicate of #62, I just forgot to release the fix.

**Closed by maltaisn** 2022-06-24 17:09 UTC
