### ISSUE TITLE
Saving a large note crashes with SQLiteBlobTooBigException and app will not start

### ISSUE THREAD

**Issue by withdrawn-auditor-craftier** [maltaisn/another-notes-app#68] opened 2022-06-24 04:36 UTC
I was copy and pasting large segments of text into the app.  It crashed (and continues to crash on startup) the the following stacktrace:

```java
FATAL EXCEPTION: main
Process: com.maltaisn.notes.sync
android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=7
at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1003)
at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:145)
at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
at a1.c.c(Unknown Source:13)
at com.maltaisn.notes.model.m$j.a(Unknown Source:21)
at com.maltaisn.notes.model.m$j.call(Unknown Source:0)
at y0.f$a$a$a$a.h(Unknown Source:89)
at v3.a.p(Unknown Source:13)
at l4.v0.run(Unknown Source:129)
at androidx.room.l0$a.run(Unknown Source:2)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:920)
```

I have not been able to start the app without it crashing.

**Comment by maltaisn** [comment] 2022-06-24 11:10
I find this surprising as the default "blob" maximum size is 1 GB. I'm not sure how you were able to copy so much text without having the app crash for other reasons before. How much text was it?

**Comment by UnknownPerson-0x00** [comment] 2022-06-24 16:00
It was no more than a few megabytes. The current app data size is 4mb with 0 cache and it continues to crash with that exception.

**Comment by maltaisn** [comment] 2022-06-24 16:17
I'll look into it but there's a chance you'll lose your data.

**Comment by maltaisn** [comment] 2022-06-24 19:17
I couldn't reproduce it, even with a 32 MB note... a shot in the dark, try this: [app-release.zip](https://github.com/maltaisn/another-notes-app/files/8980103/app-release.zip)

**Comment by maltaisn** [comment] 2023-06-27 20:50
I'll close this due to lack of information.

**Closed by maltaisn** 2023-06-27 20:50 UTC
Labels: bug
