### ISSUE TITLE
Cancel the reminder postpon causes the screen to spasm

### ISSUE THREAD

**Issue by afmbsr** [maltaisn/another-notes-app#41] opened 2021-08-13 19:12 UTC
When a reminder alert is received, the following steps result in a screen spasm and no response to clicks, except for the navigation bar:
 - From the status bar press "postpone"
 - From the calendar window, click on "Cancel"
  - Click anywhere on the screen, the result, the screen is not responding.

**Comment by maltaisn** [comment] 2021-08-13 19:49
I'm not sure if I managed to reproduce it correctly. When I click on "postpone" it brings the app up (this shouldn't happen actually!), then the dialog is shown. After cancelling the dialog, everything but the back button seems to work, although I got "app not responding" messages a few times. Is that what you're experiencing?

**Comment by maltaisn** [comment] 2021-08-13 20:46
It should be fixed. There's an "invisible screen" needed to show the dialogs, turns out it wasn't being closed on cancel.

**Comment by afmbsr** [comment] 2021-08-14 15:39
> I'm not sure if I managed to reproduce it correctly. When I click on "postpone" it brings the app up (this shouldn't happen actually!), then the dialog is shown. After cancelling the dialog, everything but the back button seems to work, although I got "app not responding" messages a few times. Is that what you're experiencing?


https://user-images.githubusercontent.com/38974362/129451500-277e35ad-61ce-4f3c-97dc-6bd3ccd31cc5.mp4

**Comment by maltaisn** [comment] 2021-08-14 21:15
Ok I didn't get that issue but I got others. It should be fixed in any case. Thanks for the report.

**Closed by maltaisn** 2021-08-14 21:15 UTC
