### ISSUE TITLE
Consider widgets

### ISSUE THREAD

**Issue by Noitarud** [maltaisn/another-notes-app#73] opened 2022-08-26 02:12 UTC
Could you have it place the note onto home screen? (I am using snotz to do this presently, like a "post it" sort of thing)

**Comment by maltaisn** [comment] 2022-08-27 00:43
Duplicate of #33

**Closed by maltaisn** 2022-08-27 00:43 UTC
Labels: enhancement

**Comment by maltaisn** [comment] 2022-08-27 00:45
Consider the app development is in support mode only, I'll fix bugs but I may not implement features for a very long time, if ever. I can take pull requests though.
